version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: library_management
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - library-network

  backend:
    build: .
    container_name: library-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: openshift
      DATABASE_URL: jdbc:mysql://mysql:3306/library_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: mysql123
      JWT_SECRET: your-256-bit-secret-key-here-make-it-long-and-secure
      CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
    networks:
      - library-network

  frontend:
    build: ./frontend
    container_name: library-frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - library-network

volumes:
  mysql_data:

networks:
  library-network:
    driver: bridge 