apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: cm9vdA==  # root (base64 encoded)
  password: bXlzcWwxMjM=  # mysql123 (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eW91ci0yNTYtYml0LXNlY3JldC1rZXktaGVyZS1tYWtlLWl0LWxvbmctYW5kLXNlY3VyZQ==  # your-256-bit-secret-key-here-make-it-long-and-secure (base64 encoded) 